name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login naar ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}        
        password: ${{ secrets.GITHUB_TOKEN }} 
    - name: Build en Push
      uses: docker/build-push-action@v5
      with:
        context: ./backend    # waar staat de Dockerfile?
        push: true
        tags: ghcr.io/${{ github.repository_owner | lower }}/open-wearables:latest
